# Generated by Django 5.2.3 on 2025-07-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="categoria",
            new_name="metPagar",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="nomePlano",
            new_name="nomeAssi",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="data_venc",
            field=models.DateField(),
        ),
    ]
