# Generated by Django 5.2.3 on 2025-07-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscription_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("entretenimento", "Entretenimento"),
                    ("musica", "Música"),
                    ("jogos", "Jogos"),
                    ("educacao", "Educação"),
                    ("produtividade", "Produtividade"),
                    ("design", "Design / Criativo"),
                    ("financeiro", "Financeiro"),
                    ("alimentacao", "Alimentação"),
                    ("saude", "Saúde"),
                    ("transporte", "Transporte"),
                    ("casa", "Casa e Serviços"),
                    ("pets", "Pets"),
                    ("compras", "Compras / Delivery"),
                    ("internet", "Internet / Dados"),
                    ("softwares", "Softwares / Apps"),
                    ("beleza", "Beleza e Estética"),
                    ("bem-estar", "Bem-estar"),
                    ("comunicacao", "Comunicação"),
                    ("outros", "Outros"),
                ],
                default="debito",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="metPagar",
            field=models.CharField(
                choices=[
                    ("debito", "Débito"),
                    ("credito", "Crédito"),
                    ("boleto", "Boleto"),
                    ("pix", "Pix"),
                ],
                default="entretenimento",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RelatorioMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("total_assinaturas", models.IntegerField()),
                (
                    "total_valor_mensal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("proximos_vencimentos", models.IntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-ano", "-mes"],
                "unique_together": {("mes", "ano")},
            },
        ),
    ]
