# Generated by Django 5.2.3 on 2025-07-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_subscription_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("atrasado", "Atrasado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
