# Generated by Django 5.2.3 on 2025-07-10 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriomensal",
            name="assinaturas_atrasadas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="relatoriomensal",
            name="assinaturas_pagas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="relatoriomensal",
            name="assinaturas_pendentes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="relatoriomensal",
            name="valor_atrasadas",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="relatoriomensal",
            name="valor_pagas",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="relatoriomensal",
            name="valor_pendentes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="relatoriomensal",
            name="proximos_vencimentos",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AssinaturaRelatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeAssi", models.CharField(max_length=100)),
                ("empresa", models.CharField(max_length=100)),
                ("data_venc", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("atrasado", "Atrasado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("entretenimento", "Entretenimento"),
                            ("musica", "Música"),
                            ("jogos", "Jogos"),
                            ("educacao", "Educação"),
                            ("produtividade", "Produtividade"),
                            ("design", "Design / Criativo"),
                            ("financeiro", "Financeiro"),
                            ("alimentacao", "Alimentação"),
                            ("saude", "Saúde"),
                            ("transporte", "Transporte"),
                            ("casa", "Casa e Serviços"),
                            ("pets", "Pets"),
                            ("compras", "Compras / Delivery"),
                            ("internet", "Internet / Dados"),
                            ("softwares", "Softwares / Apps"),
                            ("beleza", "Beleza e Estética"),
                            ("bem-estar", "Bem-estar"),
                            ("comunicacao", "Comunicação"),
                            ("outros", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "metPagar",
                    models.CharField(
                        choices=[
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("boleto", "Boleto"),
                            ("pix", "Pix"),
                        ],
                        max_length=50,
                    ),
                ),
                ("valorMens", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "relatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="subscriptions.relatoriomensal",
                    ),
                ),
            ],
        ),
    ]
