# Generated by Django 5.2.3 on 2025-07-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="telefone",
            field=models.CharField(blank=True, default=4, max_length=20),
            preserve_default=False,
        ),
    ]
