# Generated by Django 5.2.3 on 2025-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_alter_profile_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
