# Generated by Django 5.2.3 on 2025-07-14 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_subscription_data_pagamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="relatoriomensal",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="relatoriomensal",
            name="user",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="relatoriomensal",
            unique_together={("user", "mes", "ano")},
        ),
    ]
