# Generated by Django 5.2.3 on 2025-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_alter_relatoriomensal_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("atrasado", "Atrasado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
